name:   CI/CD

on: 
  push: 

  jobs: 
    linter: 
    name: Lint code base
    runs-on: ubuntu-latest

    steps:
      -name: Checkout code
      uses: actions/checkout@v2


      -name: Runner
        uses: github/linter@v3
        env: 
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
